Merge with development env
enMedD/enmedd-ai pull request #157
Opened 2024-09-27 13:01 UTC by ervinpiol

2024-09-27 21:59 UTC, SchadenKai requested changes

2024-09-27 21:59 UTC, SchadenKai commented on web/src/app/admin/users/PedingInvites.tsx
keep the current changes from the development env for now if there are no changes. The development env already have an attached endpoint to it

2024-09-27 21:59 UTC, SchadenKai commented on web/src/app/admin/users/PedingInvites.tsx
> +                            <Button>Resend Invite</Button>
comment this out first

2024-09-27 21:59 UTC, SchadenKai commented on web/src/app/admin/users/AllUsers.tsx
> +            sign up: vividsolution.io, enmedd.com, arnold.io.
the emails here are dynamic based on the `validDomains: string[]` data.
there is also a default value of message if there are no `validDomains` set

2024-09-30 07:02 UTC, ervinpiol commented on web/src/app/admin/users/PedingInvites.tsx
> +                            <Button>Resend Invite</Button>
done

2024-09-30 07:02 UTC, ervinpiol commented on web/src/app/admin/users/AllUsers.tsx
> +            sign up: vividsolution.io, enmedd.com, arnold.io.
done

2024-09-30 07:02 UTC, ervinpiol commented on web/src/app/admin/users/PedingInvites.tsx
done

2024-10-01 03:17 UTC, SchadenKai approved these changes

2024-10-01 03:17 UTC, merged